"use client";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { Provider } from "react-redux";
import store from "@/redux/store";
import { Toaster } from "react-hot-toast";
import Navbar from "./components/Navbar";
import ConnectWithUs from "./components/ConnectWithUs";
import { usePathname } from "next/navigation";
import AdminNavbar from "./pages/admin/dashboard/components/AdminNavbar";

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <Provider store={store}>
      <html lang="en">
        <body className={inter.className}>
          {pathname === "/pages/admin/dashboard" ? <AdminNavbar /> : <Navbar />}
          <Toaster />
          {children}
          {pathname !== "/pages/admin/dashboard" && <ConnectWithUs />}
        </body>
      </html>
    </Provider>
  );
}
