const members = [
  // "https://drive.google.com/uc?export=view&id=Enter your image id here" -- format used to display images form google drive in the application
  {
    name: "Aditya Waingankar",
    designation: "Lead",
    domain: "Technical",
    otherDomain: "Technical",
    img: "https://res.cloudinary.com/dkygcoyhb/image/upload/v1686071922/Ad-Astra%20Members/c1sx7humb7hczqpr1moi.jpg",
    lProfile: "https://www.linkedin.com/in/aditya-waingankar-64a6921b6",
  },
  {
    name: "Dhananjay Chaudhari",
    designation: "Lead",
    domain: "Non-Technical",
    otherDomain: "Technical",
    img: "https://res.cloudinary.com/dkygcoyhb/image/upload/v1686071761/Ad-Astra%20Members/i1xgpmggipzxznrc9whk.jpg",
    lProfile: "https://www.linkedin.com/in/dhananjay-chaudhari-810845210",
  },
  {
    name: "Sayali Chorghe",
    designation: "Lead",
    domain: "Media",
    otherDomain: "Graphics",
    img: "https://res.cloudinary.com/dkygcoyhb/image/upload/v1686071765/Ad-Astra%20Members/qbu0qmgtryjfets3jghb.jpg",
    lProfile: "https://www.linkedin.com/in/sayali-chorghe-4b73991bb/",
  },

  {
    name: "Madhura Garge",
    designation: "Co-Lead",
    domain: "Media",
    otherDomain: "Graphics",
    img: "https://res.cloudinary.com/dkygcoyhb/image/upload/v1686071762/Ad-Astra%20Members/pghp3l5vymdqz2q5zmne.jpg",
    lProfile: "https://www.linkedin.com/in/madhura-garge-40a194264/",
  },
  {
    name: "Prathamesh Zingade",
    designation: "Lead",
    domain: "Content",
    otherDomain: "Graphics",
    img: "https://res.cloudinary.com/dkygcoyhb/image/upload/v1686071761/Ad-Astra%20Members/mnfhgezvkjk6ooxtjesj.jpg",
    lProfile: "https://www.linkedin.com/in/prathamesh-zingade-8716bb210",
  },
  {
    name: "Sufiyan Chougule",
    designation: "Co-Lead",
    domain: "Content",
    otherDomain: "Content",
    img: "https://res.cloudinary.com/dkygcoyhb/image/upload/v1686071765/Ad-Astra%20Members/fuwcjzfd17juxhvsypaa.jpg",
    lProfile: "",
  },
  {
    name: "Harshita Sonkar",
    designation: "Lead",
    domain: "Graphics",
    otherDomain: "Graphics",
    img: "https://res.cloudinary.com/dkygcoyhb/image/upload/v1686071763/Ad-Astra%20Members/z60qe44rmilwmllpxirc.jpg",
    lProfile: "https://www.linkedin.com/in/harshita-sonkar-642667260/",
  },

  {
    name: "Riya Maji",
    designation: "Co-Lead",
    domain: "Graphics",
    otherDomain: "Media",
    img: "https://res.cloudinary.com/dkygcoyhb/image/upload/v1686071763/Ad-Astra%20Members/mfphgqrfugcnkce7izrr.jpg",
    lProfile: "https://www.linkedin.com/in/riya-maji-078573259/",
  },
  {
    name: "Raj Padval",
    designation: "Core",
    domain: "Technical",
    otherDomain: "Technical",
    img: "https://res.cloudinary.com/dkygcoyhb/image/upload/v1686071772/Ad-Astra%20Members/czh6wrrunzuyv33lojrl.jpg",
    lProfile: "https://www.linkedin.com/in/raj-padval-10869125b/",
  },

  {
    name: "Diptimai Sahoo",
    designation: "Core",
    domain: "Technical",
    otherDomain: "Technical",
    img: "https://res.cloudinary.com/dkygcoyhb/image/upload/v1686071762/Ad-Astra%20Members/twywb49mw5xmcetsnmlf.jpg",
    lProfile: "https://www.linkedin.com/in/diptimai-sahoo-7b79a122a/",
  },

  {
    name: "Vivek Kumbhar",
    designation: "Core",
    domain: "Content",
    otherDomain: "Content",
    img: "https://res.cloudinary.com/dkygcoyhb/image/upload/v1686071764/Ad-Astra%20Members/s3onvhi069cmiky1cykw.jpg",
    lProfile: "",
  },
  {
    name: "Shubham kushwaha",
    designation: "Core",
    domain: "Technical",
    otherDomain: "Technical",
    img: "https://res.cloudinary.com/dkygcoyhb/image/upload/v1686071762/Ad-Astra%20Members/kkojswm3usgvyhcc5trb.jpg",
    lProfile: "https://www.linkedin.com/in/shubham-kushwaha-135221214/",
  },
  {
    name: "Akansha Puri",
    designation: "Core",
    domain: "Graphics",
    otherDomain: "Graphics",
    img: "https://res.cloudinary.com/dkygcoyhb/image/upload/v1686071761/Ad-Astra%20Members/e1qpwz0y0o1wobjuokgs.jpg",
    lProfile: "",
  },
  {
    name: "Nikita Varma",
    designation: "Core",
    domain: "Non-Technical",
    otherDomain: "Non-Technical",
    img: "https://res.cloudinary.com/dkygcoyhb/image/upload/v1686071764/Ad-Astra%20Members/uuw29w9uqxpier69vx2n.jpg",
    lProfile: "https://www.linkedin.com/in/nikita-varma-14034922b/",
  },

  {
    name: "Neha Bagul",
    designation: "Core",
    domain: "Content",
    otherDomain: "Content",
    img: "https://res.cloudinary.com/dkygcoyhb/image/upload/v1686071764/Ad-Astra%20Members/olikipwzo8hvtumkxo7j.jpg",
    lProfile: "",
  },
];

export default members;
